/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./components/BaseFooter.vue')['default']
    GreetFromRust: typeof import('./components/GreetFromRust.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
